import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Check, ChevronRight, FileText } from "lucide-react";
import { notFound } from "next/navigation";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

type ProductPageProps = { params: { slug: string } };

export async function generateStaticParams() {
  const { companyDetails } = await import("@/config/companyDetails");
  return companyDetails.products.map((product) => ({ slug: product.slug }));
}

export async function generateMetadata({ params }: ProductPageProps): Promise<Metadata> {
  const { companyDetails } = await import("@/config/companyDetails");
  const product = companyDetails.products.find((item) => item.slug === params.slug);
  if (!product) return { title: "Product not found" };
  return { title: `${product.name} | ${companyDetails.branding.name}`, description: product.shortDescription };
}

export default async function ProductDetailPage({ params }: ProductPageProps) {
  const { companyDetails } = await import("@/config/companyDetails");
  const product = companyDetails.products.find((item) => item.slug === params.slug);
  if (!product) notFound();
  const relatedProducts = companyDetails.products.filter((item) => item.category === product.category && item.slug !== product.slug).slice(0, 3);
  const productSchema = { "@context": "https://schema.org", "@type": "Product", name: product.name, description: product.description, category: product.categoryLabel, brand: { "@type": "Brand", name: companyDetails.branding.name }, additionalProperty: product.specifications.map((specification) => ({ "@type": "PropertyValue", name: specification.label, value: specification.value })) };

  return <><Navbar /><main>
    <section className="bg-white py-8 sm:py-10"><div className="page-shell"><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-1.5 text-sm text-muted"><Link href="/" className="hover:text-brand focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">Home</Link><ChevronRight aria-hidden="true" className="size-4" /><Link href="/products" className="hover:text-brand focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">Products</Link><ChevronRight aria-hidden="true" className="size-4" /><span aria-current="page" className="font-medium text-ink">{product.name}</span></nav></div></section>
    <section className="border-y border-slate-200 bg-canvas py-10 sm:py-16"><div className="page-shell grid gap-10 lg:grid-cols-2 lg:items-center"><div className="relative aspect-[1.1] overflow-hidden rounded-card bg-slate-200 shadow-enterprise"><Image src={product.image} alt={product.imageAlt} fill priority sizes="(min-width: 1024px) 50vw, 100vw" placeholder="blur" blurDataURL={product.blurDataURL} className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-navy/25 to-transparent" /></div><div><p className="eyebrow">{product.categoryLabel}</p><h1 className="mt-4 font-display text-4xl leading-[1.08] font-semibold tracking-[-0.055em] text-ink sm:text-5xl">{product.name}</h1><p className="mt-5 max-w-xl text-base leading-7 text-muted sm:text-lg">{product.description}</p><div className="mt-6 flex flex-wrap gap-2">{product.badges.map((badge) => <span key={badge} className="rounded-full bg-brand/10 px-3 py-1.5 text-sm font-bold text-brand">{badge}</span>)}</div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="button-primary inline-flex items-center justify-center gap-2 bg-brand px-6 text-white shadow-floating">Enquire about this product <ArrowUpRight aria-hidden="true" className="size-4" /></Link><a href={`mailto:${companyDetails.contact.email}?subject=${encodeURIComponent(`Request brochure: ${product.name}`)}`} className="button-outline inline-flex items-center justify-center gap-2 px-6"><FileText aria-hidden="true" className="size-4" />Request brochure</a></div></div></div></section>
    <section className="section-space bg-white"><div className="page-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Key specifications</p><h2 className="section-title mt-4">Built for confident everyday performance.</h2><p className="mt-5 max-w-md leading-7 text-muted">Our team will help you confirm the precise configuration, availability, and installation requirements for your environment.</p></div><dl className="grid overflow-hidden rounded-card border border-slate-200 sm:grid-cols-2">{product.specifications.map((specification) => <div key={specification.label} className="border-b border-slate-200 p-5 sm:nth-[odd]:border-r"><dt className="text-xs font-bold tracking-[0.13em] text-muted uppercase">{specification.label}</dt><dd className="mt-2 text-sm font-semibold leading-6 text-ink">{specification.value}</dd></div>)}</dl></div></section>
    <section className="bg-canvas py-20 sm:py-28"><div className="page-shell grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Ideal applications</p><h2 className="section-title mt-4">Made for spaces like yours.</h2></div><div className="grid gap-4 sm:grid-cols-3">{product.applications.map((application, index) => <div key={application} className="rounded-card border border-slate-200 bg-white p-6 shadow-enterprise"><p className="font-display text-lg font-semibold text-brand">0{index + 1}</p><p className="mt-5 text-base font-semibold text-ink">{application}</p><Check aria-hidden="true" className="mt-5 size-5 text-mint" /></div>)}</div></div></section>
    {relatedProducts.length > 0 && <section className="bg-white py-20 sm:py-28"><div className="page-shell"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Explore more</p><h2 className="section-title mt-4">Related {product.categoryLabel.toLowerCase()}.</h2></div><Link href={`/products?category=${product.category}`} className="inline-flex items-center gap-2 text-sm font-bold text-brand hover:text-sky focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">View category <ArrowUpRight aria-hidden="true" className="size-4" /></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{relatedProducts.map((item) => <Link key={item.slug} href={`/products/${item.slug}`} className="group overflow-hidden rounded-card border border-slate-200 bg-canvas shadow-enterprise transition-[transform,box-shadow] hover:-translate-y-1 hover:shadow-floating focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"><div className="relative aspect-[1.55]"><Image src={item.image} alt={item.imageAlt} fill sizes="(min-width: 768px) 33vw, 100vw" placeholder="blur" blurDataURL={item.blurDataURL} className="object-cover transition-transform duration-700 group-hover:scale-105" /></div><div className="p-5"><p className="font-display text-lg font-semibold text-ink">{item.name}</p><p className="mt-2 text-sm leading-5 text-muted">{item.shortDescription}</p></div></Link>)}</div></div></section>}
    <section className="bg-navy py-14 text-white"><div className="page-shell flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display text-2xl font-semibold tracking-[-0.04em]">Need help choosing the right configuration?</p><p className="mt-2 text-sm text-slate-300">Speak with GALTech about your space and requirements.</p></div><Link href="/products" className="inline-flex items-center gap-2 text-sm font-bold text-cyan-100 hover:text-mint focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-mint"><ArrowLeft aria-hidden="true" className="size-4" />Back to all products</Link></div></section>
  </main><Footer /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema).replace(/</g, "\\u003c") }} /></>;
}
